### ISSUE TITLE
！！！你这个哲学♂搜索有毒♂呀，

### ISSUE THREAD

**Issue by alwaysused** [LanFD/music_163#1]
随手搜了首歌，结果传来了哲学♂的声音...
不打算做个列表吗。

**Comment by LanFD** [comment]
一定是你搜索的♂姿势♂不对！有空再加列表吧，年底好多事情

**Comment by alwaysused** [comment]
我刚才又试了一下， 就比如我搜索“花田错”（王力宏的一首歌），每次按回车搜索之后播放的歌都不一样，比如可能是王力宏唱的，也可能是别人的翻唱版本，  昨天第一次搜，结果传来了“啊♂啊”的声音……
         我还以为每次按搜索一样的歌都会播放搜索到的列表里的第一首歌所以放出来的歌也是一样的，看起来不是这样呀。可能每次网易返回的列表歌曲顺序是不同的，或者说你对返回的数据处理了一下？
   打扰了，圣诞♂节快乐。

**Comment by LanFD** [comment]
我是先搜索到关键字获取的歌曲总数然后随机播放其中一首，并不是播放首曲。他的歌曲列表貌似一定时间内是不变的，之后就会变，应当是做了搜索缓存。♂圣诞♂快乐。
